name: QA

on:
    push:
        branches:
            - master

jobs:
    backend:
        runs-on: ubuntu-18.04
        steps:
          - uses: docker/build-push-action@v1
          - with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
              repository: eriktrapman/kubtest-php
              tag_with_ref: true
              tag_with_sha: true
              dockerfile: 'deployment/Dockerfile'
